# Generated by Django 4.1.1 on 2022-10-11 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academic', '0002_order_category_order_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='order',
            new_name='Assignment',
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Academic.assignment')),
            ],
        ),
    ]
