# Generated by Django 4.1.1 on 2022-10-11 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academic', '0003_rename_order_assignment_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Academic.tutor'),
        ),
    ]
