# Generated by Django 4.1.1 on 2022-10-16 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academic', '0005_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('file', models.FileField(null=True, upload_to='images')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='description',
            new_name='instructions',
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
        migrations.AddField(
            model_name='answer',
            name='assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Academic.assignment'),
        ),
    ]
