# Generated by Django 4.1.1 on 2022-10-16 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academic', '0006_answer_rename_description_assignment_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Academic.tutor'),
        ),
    ]
