# Generated by Django 4.1.1 on 2022-10-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academic', '0010_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('2', 'TUTOR'), ('1', 'STUDENT')], default=1, max_length=25),
        ),
    ]
