# Generated by Django 4.1.1 on 2022-10-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academic', '0011_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
