# Generated by Django 4.1.1 on 2022-10-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academic', '0012_alter_student_id_alter_tutor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
